### ISSUE TITLE
1.16.4 shulkerbox.sc NullPointerException with collision mode

### ISSUE THREAD

**Issue by Meeni-mc** [gnembon/scarpet#153]
## Problem

When using 'collision' mode, the following error is spamming the chat:

```
[02:21:30] [Server thread/INFO]: [Sand: Callback failed:       modify(e, 'pickup_delay', 1);
       HERE>> entity_event(e, 'on_tick', null);
   ,
Error while evaluating expression: java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "lzargs" is null in shulkerboxes at line 94, pos 7]
[02:21:30] [main/INFO]: [CHAT] [02:21:30] [Sand: Callback failed:       modify(e, 'pickup_delay', 1);\n       HERE>> entity_event(e, 'on_tick', null);\n   ,\nError while evaluating expression: java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "lzargs" is null in shulkerboxes at line 94, pos 7]
[02:21:31] [Server thread/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "lzargs" is null
```

The 'Vacuum' feature appears to work normally nonetheless.

No error is reported in 'pickup' mode. 

### Setup

* Minecraft 1.16.4
* fabric-loader-0.10.6+build.214.jar
* fabric-api-0.25.1+build.416-1.16
* fabric-carpet-1.16.4-1.4.15+v201102
* jdk-15.0.0.36-hotspot

### Full error, from the game error log:

```
[02:21:30] [Server thread/INFO]: [Sand: Callback failed:       modify(e, 'pickup_delay', 1);
       HERE>> entity_event(e, 'on_tick', null);
   ,
Error while evaluating expression: java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "lzargs" is null in shulkerboxes at line 94, pos 7]
[02:21:30] [main/INFO]: [CHAT] [02:21:30] [Sand: Callback failed:       modify(e, 'pickup_delay', 1);\n       HERE>> entity_event(e, 'on_tick', null);\n   ,\nError while evaluating expression: java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "lzargs" is null in shulkerboxes at line 94, pos 7]
[02:21:31] [Server thread/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "lzargs" is null
[02:21:31] [Server thread/INFO]: [STDERR]: 	at carpet.script.value.FunctionValue.resolveArgs(FunctionValue.java:280)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at carpet.script.api.Entities.lambda$apply$30(Entities.java:305)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at carpet.script.Expression$10.lazyEval(Expression.java:333)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at carpet.script.Expression.lambda$getAST$8(Expression.java:682)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at carpet.script.language.ControlFlow.lambda$apply$1(ControlFlow.java:17)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at carpet.script.Expression$4.lazyEval(Expression.java:220)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at carpet.script.Expression.lambda$getAST$5(Expression.java:647)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at carpet.script.language.ControlFlow.lambda$apply$5(ControlFlow.java:31)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at carpet.script.Expression$10.lazyEval(Expression.java:333)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at carpet.script.Expression.lambda$getAST$8(Expression.java:682)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at carpet.script.language.ControlFlow.lambda$apply$1(ControlFlow.java:17)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at carpet.script.Expression$4.lazyEval(Expression.java:220)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at carpet.script.Expression.lambda$getAST$5(Expression.java:647)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at carpet.script.value.FunctionValue.lazyEval(FunctionValue.java:221)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at carpet.script.CarpetScriptHost.lambda$callUDF$7(CarpetScriptHost.java:387)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at carpet.script.Expression.evalValue(Expression.java:604)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at carpet.script.CarpetScriptHost.callUDF(CarpetScriptHost.java:386)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at carpet.script.CarpetScriptServer.runas(CarpetScriptServer.java:340)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at carpet.script.CarpetScriptServer.runas(CarpetScriptServer.java:330)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at carpet.script.CarpetEventServer$Callback.execute(CarpetEventServer.java:90)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at carpet.script.EntityEventsGroup$Event.call(EntityEventsGroup.java:121)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at carpet.script.EntityEventsGroup.onEvent(EntityEventsGroup.java:46)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1297.handler$cdf000$onTickCall(class_1297.java:7183)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1297.method_5773(class_1297.java)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1542.method_5773(class_1542.java:95)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3218.method_18762(class_3218.java:621)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1937.method_18472(class_1937.java:561)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3218.method_18765(class_3218.java:411)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1132.method_3748(class_1132.java:91)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.handler$bok000$modifiedRunLoop(MinecraftServer.java:5810)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:651)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
[02:21:31] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:832)
[02:21:31] [Server thread/INFO]: [Sand: Callback failed:       modify(e, 'pickup_delay', 1);
       HERE>> entity_event(e, 'on_tick', null);
   ,
Error while evaluating expression: java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "lzargs" is null in shulkerboxes at line 94, pos 7]
[02:21:31] [main/INFO]: [CHAT] [02:21:31] [Sand: Callback failed:       modify(e, 'pickup_delay', 1);\n       HERE>> entity_event(e, 'on_tick', null);\n   ,\nError while evaluating expression: java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "lzargs" is null in shulkerboxes at line 94, pos 7]
[02:21:32] [Server thread/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "lzargs" is null
[02:21:32] [Server thread/INFO]: [STDERR]: 	at carpet.script.value.FunctionValue.resolveArgs(FunctionValue.java:280)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at carpet.script.api.Entities.lambda$apply$30(Entities.java:305)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at carpet.script.Expression$10.lazyEval(Expression.java:333)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at carpet.script.Expression.lambda$getAST$8(Expression.java:682)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at carpet.script.language.ControlFlow.lambda$apply$1(ControlFlow.java:17)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at carpet.script.Expression$4.lazyEval(Expression.java:220)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at carpet.script.Expression.lambda$getAST$5(Expression.java:647)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at carpet.script.language.ControlFlow.lambda$apply$5(ControlFlow.java:31)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at carpet.script.Expression$10.lazyEval(Expression.java:333)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at carpet.script.Expression.lambda$getAST$8(Expression.java:682)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at carpet.script.language.ControlFlow.lambda$apply$1(ControlFlow.java:17)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at carpet.script.Expression$4.lazyEval(Expression.java:220)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at carpet.script.Expression.lambda$getAST$5(Expression.java:647)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at carpet.script.value.FunctionValue.lazyEval(FunctionValue.java:221)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at carpet.script.CarpetScriptHost.lambda$callUDF$7(CarpetScriptHost.java:387)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at carpet.script.Expression.evalValue(Expression.java:604)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at carpet.script.CarpetScriptHost.callUDF(CarpetScriptHost.java:386)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at carpet.script.CarpetScriptServer.runas(CarpetScriptServer.java:340)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at carpet.script.CarpetScriptServer.runas(CarpetScriptServer.java:330)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at carpet.script.CarpetEventServer$Callback.execute(CarpetEventServer.java:90)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at carpet.script.EntityEventsGroup$Event.call(EntityEventsGroup.java:121)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at carpet.script.EntityEventsGroup.onEvent(EntityEventsGroup.java:46)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1297.handler$cdf000$onTickCall(class_1297.java:7183)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1297.method_5773(class_1297.java)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1542.method_5773(class_1542.java:95)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3218.method_18762(class_3218.java:621)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1937.method_18472(class_1937.java:561)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3218.method_18765(class_3218.java:411)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1132.method_3748(class_1132.java:91)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.handler$bok000$modifiedRunLoop(MinecraftServer.java:5810)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:651)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
[02:21:32] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:832)
[02:21:32] [Server thread/INFO]: [Sand: Callback failed:       modify(e, 'pickup_delay', 1);
       HERE>> entity_event(e, 'on_tick', null);
   ,
Error while evaluating expression: java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "lzargs" is null in shulkerboxes at line 94, pos 7]
[02:21:32] [main/INFO]: [CHAT] [02:21:32] [Sand: Callback failed:       modify(e, 'pickup_delay', 1);\n       HERE>> entity_event(e, 'on_tick', null);\n   ,\nError while evaluating expression: java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "lzargs" is null in shulkerboxes at line 94, pos 7]
```

**Comment by gnembon** [comment]
I  believe that was indeed a bug and was fixed in a newer carpet. Please update and thanks for reporting.
